#!/bin/bash

# This script adds ssh to your current local repo for authentication.

# eval "$(ssh-agent -s)"

eval "$(ssh-agent)"

ssh-add ~/.ssh/"$1"

ssh -T git@github.com

git remote set-url origin "$2"

bash -i
